-- Presentation history for repeated songs and reports.

create table if not exists music_manager.song_presentations (
  id bigint generated by default as identity primary key,
  song_id bigint not null references music_manager.songs(id) on delete cascade,
  presented_on date not null default current_date,
  presented_by uuid references music_manager.profiles(id),
  notes text,
  created_at timestamptz not null default now(),
  unique (song_id, presented_on)
);

create index if not exists song_presentations_song_id_idx
on music_manager.song_presentations(song_id);

create index if not exists song_presentations_presented_on_idx
on music_manager.song_presentations(presented_on desc);

grant select, insert on music_manager.song_presentations to authenticated;
grant usage, select on sequence music_manager.song_presentations_id_seq to authenticated;

comment on table music_manager.song_presentations is
'Dated history of songs that have been presented by the team.';

comment on column music_manager.song_presentations.presented_on is
'Date when the song was presented.';

comment on column music_manager.song_presentations.presented_by is
'Profile id of the logged-in user who marked the song as presented.';

notify pgrst, 'reload schema';
