-- Document-style Consecration piano beat headers with ordered songs below each beat.

create table if not exists music_manager.consecration_beat_groups (
  id bigint generated by default as identity primary key,
  title text not null default 'Consecration Songs',
  beat_name text not null,
  beat_category text,
  tempo int,
  variation text,
  notes text,
  created_by uuid references music_manager.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists music_manager.consecration_beat_group_songs (
  id bigint generated by default as identity primary key,
  group_id bigint not null references music_manager.consecration_beat_groups(id) on delete cascade,
  song_id bigint not null references music_manager.songs(id) on delete cascade,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique (group_id, song_id)
);

create index if not exists consecration_beat_groups_created_at_idx
on music_manager.consecration_beat_groups(created_at desc);

create index if not exists consecration_beat_group_songs_group_order_idx
on music_manager.consecration_beat_group_songs(group_id, sort_order);

comment on table music_manager.consecration_beat_groups is
'Piano beat/style headers for Consecration song groupings copied from team documents.';

comment on table music_manager.consecration_beat_group_songs is
'Ordered songs shown beneath a Consecration piano beat/header.';

grant select, insert on music_manager.consecration_beat_groups to authenticated;
grant select, insert on music_manager.consecration_beat_group_songs to authenticated;

grant usage, select on sequence music_manager.consecration_beat_groups_id_seq to authenticated;
grant usage, select on sequence music_manager.consecration_beat_group_songs_id_seq to authenticated;

notify pgrst, 'reload schema';
