-- Public song suggestions submitted for review and later inclusion.

create table if not exists music_manager.song_suggestions (
  id bigint generated by default as identity primary key,
  song_name text not null,
  suggestion_area text not null default 'consecration'
    check (suggestion_area in ('consecration', 'presentation', 'library', 'other')),
  suggester_name text,
  expected_presentation text,
  details text,
  status text not null default 'new'
    check (status in ('new', 'reviewed', 'added', 'declined')),
  created_by uuid references music_manager.profiles(id),
  suggester_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists song_suggestions_created_at_idx
on music_manager.song_suggestions(created_at desc);

create index if not exists song_suggestions_area_status_idx
on music_manager.song_suggestions(suggestion_area, status);

comment on table music_manager.song_suggestions is
'Song suggestions submitted before they are added to Consecration, Presentation, or the main library.';

grant select, insert, update, delete on music_manager.song_suggestions to authenticated;
grant insert on music_manager.song_suggestions to anon;
grant usage, select on sequence music_manager.song_suggestions_id_seq to authenticated;
grant usage, select on sequence music_manager.song_suggestions_id_seq to anon;

notify pgrst, 'reload schema';
